export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  REGISTER_STUDENT: "/register/student",
  REGISTER_PROFESSOR: "/register/professor",
  REGISTER_LOCATEUR: "/register/locateur",
  ADD_PARTENAIRE: "/addPartenaire",
  COLOCATIONS: "/colocations",
  REVISIONS: "/revisions",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  SECURITY: "/security",
  SUPPORT: "/support",
  DASHBOARD: "/dashboard",
  ADD_HOUSE: "/addHouse",
  HOME_DETAILS: "/home",
  ADMIN: "/admin",
  ADMIN_HOMES: "/admin/manage-homes",
  ADMIN_REVISIONS: "/admin/manage-revisions",
  ADMIN_USERS: "/admin/users",
  ADMIN_SIGNALES: "/admin/manage-signales",
};
